server:
  port: 8080

#h2 database properties
#spring:
#  h2:
#    console.enabled: true
#  datasource:
#    url: jdbc:h2:mem:mydb
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    defer-datasource-initialization: true
#    database-platform: org.hibernate.dialect.H2Dialect

spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/cinema_db?createDatabaseIfNotExist=true
    username: root  # your db user name
    password: root  # your db user password
    driverClassName: com.mysql.cj.jdbc.Driver
  data:
    jpa:
      repositories:
        enabled: true

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    # 1h in millisecond
    expiration-time: 3600000

logging:
  level:
    org:
      springframework: DEBUG
      hibernate: DEBUG